--- 
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
spec: {}
status: {}
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
spec: {}
status: {}

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
spec: {}
status: {}
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: minio
spec: {}
status: {}

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: spark
spec: {}
status: {}
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: spark-operator
spec: {}
status: {}